### ISSUE TITLE
区块中包括交易实体吗？

### ISSUE THREAD

**Issue by fengbo-1013** [Hyperledger-TWGC/TWGC-FAQ#3]
根据Fabric官方文档，区块（block）包括block header、block data和block metadata，block data包含交易记录。请问交易记录包含哪些数据单元（数据项）？可以包含交易实体（如订单内容或订单内容的Hash值）吗？如果包含，放在哪个数据项？这个数据项是否可以以数组形式，即以hash数组形式保存吗？

**Comment by davidkhala** [comment]
https://github.com/Hyperledger-TWGC/TWGC-FAQ/blob/main/fabricV1Block.png
@fengbo-1013 
这个1版本的图应该能解释大部分的问题哈

**Comment by fengbo-1013** [comment]
@davidkhala 图片在哪里？

**Comment by davidkhala** [comment]
就在我上面的评论里 是没法加载么？

**Comment by fengbo-1013** [comment]
无法加载。看不到。可发邮件给我bertfeng@hotmail.com

发自我的iPhone

**Comment by davidkhala** [comment]
> 无法加载。看不到。可发邮件给我bertfeng@hotmail.com
> 
> 发自我的iPhone
> 
> > 在 2021年2月4日，下午6:27，David Liu <notifications@github.com> 写道：
> > 
> > ﻿
> > 就在我上面的评论里 是没法加载么？
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

应该是图的链接被墙了. I replace it with a non direct image link.

**Comment by davidkhala** [comment]
Answered and added in https://github.com/Hyperledger-TWGC/TWGC-FAQ/commit/27f485832ebe7976938710b61cc367752c68d1bb
 

Close
