### ISSUE TITLE
fabric如何实现跨通道传输区块？

### ISSUE THREAD

**Issue by fengbo-1013** [Hyperledger-TWGC/TWGC-FAQ#4]
我们的项目希望实现跨通道转移区块，即：当前通道不需要经过背书交易、生成区块等步骤，而是从上一个通道中直接读取区块然后在当前通道进行分发。可以实现吗？如何实现？

**Comment by davidkhala** [comment]
通道可以理解成一个相对独立的子链。
相关的功能应该不能实现

**Comment by fengbo-1013** [comment]
@davidkhala 既然能跨通道读区块，为什么没有办法写到当前区块呢？是否有办法实现？

**Comment by davidkhala** [comment]
通常在合约层面并不读区块，只能读取其他通道的世界状态。不允许在一般性交易周期当中跨通道写的原因是出于共识安全的考虑。不过在中间件层总是可以实现的，这部分就不属于fabric自己的范畴了
此外就是标题里的需求和一般的区块链设计是相违背的，不经过既定的共识是不能新增区块的。
