### ISSUE TITLE
两台云服务器进行多机部署的时候，创建通道出问题

### ISSUE THREAD

**Issue by wuzi983** [Hyperledger-TWGC/TWGC-FAQ#7]
报错如下：failed to create deliver client for orderer: orderer client failed to connect to orderer0.example.com:7050: failed to create new connection: context deadline exceeded。使用docker ps查看各端口，域名映射如下。同时使用netstat-tplugn查看各个端口
[issure.pdf](https://github.com/Hyperledger-TWGC/FAQ/files/6212320/issure.pdf)
。同时防火墙关闭，使用的是腾讯云centos 7.6版本，fabric2.0

**Comment by davidkhala** [comment]
云服务以及网络问题不做回答
